debug_log: false

kafka:
  consumers:
    maj_amex_request:
      bootstrap_servers: 'kafka:9092'
      topic: 'bigmom.spreading.requests.process'
      auto_offset_reset: 'earliest'
      group_id: 'bigmom-job-spread-amx'
      auto_commit: False
      auto_commit_interval_ms: 1000
      max_poll_interval_ms: 600000
  producers:
    maj_amex_response:
      bootstrap_servers: 'kafka:9092'
      topic: 'bigmom.spreading.responses.process'

job_properties:
  job_amex_property: 'job-spread-amx'

ace_bdd:
  hostname: "192.168.201.201"
  username: "oracle"
  password: "oraexpa1"
  oracle_env: ". /home/oracle/.bash_profile ; "
  timeout: 10